resetButton
ozanyerli/turkeyvisited pull request #10
Opened 2024-05-24 23:08 UTC by sb-exe-calismayi-durdurdu

- `Sıfırla` butonu eklendi.
- Bu buton hem lokali hem harita renklerini hem de counterı sıfırlıyor.
- `Bölgeler` butonu kaldırıldı.

2024-05-26 12:05 UTC, ozanyerli requested changes
Elinize sağlık.

Bence sıfırla butonu indirme butonun üstünde olsa daha güzel olur. Bir de Github logosunun kaydığını görüyorum. Orijinal yerinde kalmalı.

![image](https://github.com/ozanyerli/turkeyvisited/assets/43146149/4f1fc168-af75-482e-a68f-95bf547bbe5f)

Bu değişikliklerden sonra mergeleyebiliriz.

2024-05-26 16:32 UTC, sb-exe-calismayi-durdurdu commented
Bu yolladığım kodlarda dediğiniz şekilde biçimlendirmeye çalıştım: #11

2024-05-31 01:52 UTC, sb-exe-calismayi-durdurdu commented
Git Bash'ten PR'e ulaşıp logo ve buton konumlarını değiştirebildim ama geri pushlayıp PR'i güncelleyemedim. Bu yüzden Github'tan direkt manuel olarak istediğiniz değişiklikleri yapmaya çalıştım. Umarım atladığım bir nokta olmamıştır.

2024-06-02 10:22 UTC, ozanyerli approved these changes
Elinize sağlık. Bu hali uygundur. Mergeliyorum.

PR değil de branch üzerinde çalışmanız gerekiyor, muhtemelen o sebeple sorun yaşadınız. PR'ı GitHub'ın eklediği bir fonksiyonalite olarak düşünebilirsiniz, normalde git'in bir parçası değil. Aslolan şey sizin açtığınız branch. O sebeple git bash değil direkt git komutlarıyla`resetButton-24-05-24` branchine geçip orada değişiklikleri yapabilirsiniz.

2024-06-02 10:22 UTC, merged

2024-06-02 15:39 UTC, sb-exe-calismayi-durdurdu commented
Bunu öğrendiğim çok iyi oldu teşekkürler. Git Bash'te elli saat PR açmaya çalıştım :) Branch üzerinden gitmek gerekiyormuş cidden.

2025-08-28 18:34 UTC, ertugrul-yazilim commented
Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz mısın. iller ve ilçeler bir arada. bir türlü yapamadım

2025-08-28 19:32 UTC, samilboyalikli commented
> Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz mısın. iller ve ilçeler bir arada. bir türlü yapamadım

Selamlar.

Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (https://github.com/ozanyerli). Ben şehirlerin sayısını hem arayüzden hem de local storage'den sıfırlayan kısmı ekledim.
Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım kadarıyla `tr-cities.json` dosyasında ilçelerin koordinatlarını ve isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor. Sonrasında `turkeyvisited.js`'i ona göre revize etmek gerekebilir.

Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz etkiyi oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz yönde etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret ettiğime pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor olabilirim.

2025-08-28 19:41 UTC, ertugrul-yazilim commented
Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak istiyorum
kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına tercih
verdiğini türliye haritası üzerinden görsün istedim

28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***>
şunu yazdı:

> *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>
>
> Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz mısın.
> iller ve ilçeler bir arada. bir türlü yapamadım
>
> Selamlar.
>
> Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (
> https://github.com/ozanyerli). Ben şehirlerin sayısını hem arayüzden hem
> de local storage'den sıfırlayan kısmı ekledim.
> Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım
> kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve
> isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor.
> Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir.
>
> Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz etkiyi
> oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz yönde
> etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret ettiğime
> pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat
> ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor olabilirim.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-08-28 19:51 UTC, samilboyalikli commented
Anlıyorum. Gayet güzel düşünmüşsünüz, özellikle memur adaylarının
kullanabileceği birşey bu. Peki hangi noktada problem oldu?

Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:41
tarihinde şunu yazdı:

> *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>
> Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak
> istiyorum
> kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına tercih
> verdiğini türliye haritası üzerinden görsün istedim
>
> 28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***>
> şunu yazdı:
>
> > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>
>
> >
> > Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz mısın.
> > iller ve ilçeler bir arada. bir türlü yapamadım
> >
> > Selamlar.
> >
> > Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (
> > https://github.com/ozanyerli). Ben şehirlerin sayısını hem arayüzden
> hem
> > de local storage'den sıfırlayan kısmı ekledim.
> > Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım
> > kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve
> > isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor.
> > Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir.
> >
> > Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz etkiyi
> > oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz
> yönde
> > etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret
> ettiğime
> > pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat
> > ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor olabilirim.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBN63F6XGZOILJF5HOZ2GI33P5LO5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4ZDMMZTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-08-28 19:53 UTC, ertugrul-yazilim commented
Aslında ben yazılıma sadece ilgiliyim dillere hakim değilim. Cursor ile
fikrimi hayata geçirmeye çalıştım o da beceremedi sizin gibi dinamik harita
eklemeyi

28 Ağu 2025 Per 22:51 tarihinde Samil BOYALIKLI ***@***.***>
şunu yazdı:

> *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>
> Anlıyorum. Gayet güzel düşünmüşsünüz, özellikle memur adaylarının
> kullanabileceği birşey bu. Peki hangi noktada problem oldu?
>
> Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:41
> tarihinde şunu yazdı:
>
> > *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>
>
> > Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak
> > istiyorum
> > kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına tercih
> > verdiğini türliye haritası üzerinden görsün istedim
> >
> > 28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***>
> > şunu yazdı:
> >
> > > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>
>
> >
> > >
> > > Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz
> mısın.
> > > iller ve ilçeler bir arada. bir türlü yapamadım
> > >
> > > Selamlar.
> > >
> > > Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (
> > > https://github.com/ozanyerli). Ben şehirlerin sayısını hem arayüzden
> > hem
> > > de local storage'den sıfırlayan kısmı ekledim.
> > > Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım
> > > kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve
> > > isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor.
> > > Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir.
> > >
> > > Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz etkiyi
> > > oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz
> > yönde
> > > etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret
> > ettiğime
> > > pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat
> > > ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor olabilirim.
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BBN63F6XGZOILJF5HOZ2GI33P5LO5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4ZDMMZTGI>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BUOIQJBHWL4QOZC6CDT6J6L3P5MT5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TCMBRG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-08-28 20:06 UTC, samilboyalikli commented
Anladım. Öncelikle sıfırdan harita kurgulamak zorunda değilsiniz. Mevcut
datasete ilçeler eklenerek ilerlenebilir. PR'lara bakarsanız bir
arkadaşımız KKTC'ni de eklediği bir versiyon yollamış mesela (
https://github.com/ozanyerli/turkeyvisited/pull/13). Buradaki kodları
incelerseniz, aslında contributor adayı yalnızca tr-cities.json dosyasına
KKTC'nin koordinatlarını ve özelliklerini ekleyip turkeyvisited.js'i buna
göre revize etmiş.

Ben ne yazık ki yoğunluğumdan dolayı buna vakit ayıramam ama burada kilit
noktanın tr-cities.json dosyası olduğunu düşünüyorum. Buradan yola
çıkarsanız istediğiniz sonuca daha rahat ulaşabilirsiniz.

Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:53
tarihinde şunu yazdı:

> *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435>
> Aslında ben yazılıma sadece ilgiliyim dillere hakim değilim. Cursor ile
> fikrimi hayata geçirmeye çalıştım o da beceremedi sizin gibi dinamik
> harita
> eklemeyi
>
> 28 Ağu 2025 Per 22:51 tarihinde Samil BOYALIKLI ***@***.***>
> şunu yazdı:
>
> > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>
>
> > Anlıyorum. Gayet güzel düşünmüşsünüz, özellikle memur adaylarının
> > kullanabileceği birşey bu. Peki hangi noktada problem oldu?
> >
> > Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:41
> > tarihinde şunu yazdı:
> >
> > > *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>
>
> >
> > > Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak
> > > istiyorum
> > > kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına
> tercih
> > > verdiğini türliye haritası üzerinden görsün istedim
> > >
> > > 28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***>
> > > şunu yazdı:
> > >
> > > > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > > > <
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>
>
> >
> > >
> > > >
> > > > Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz
> > mısın.
> > > > iller ve ilçeler bir arada. bir türlü yapamadım
> > > >
> > > > Selamlar.
> > > >
> > > > Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (
> > > > https://github.com/ozanyerli). Ben şehirlerin sayısını hem
> arayüzden
> > > hem
> > > > de local storage'den sıfırlayan kısmı ekledim.
> > > > Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım
> > > > kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve
> > > > isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor.
> > > > Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir.
> > > >
> > > > Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz
> etkiyi
> > > > oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz
> > > yönde
> > > > etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret
> > > ettiğime
> > > > pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat
> > > > ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor
> olabilirim.
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY>
>
> >
> > >
> > > > .
> > > > You are receiving this because you commented.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BBN63F6XGZOILJF5HOZ2GI33P5LO5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4ZDMMZTGI>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BUOIQJBHWL4QOZC6CDT6J6L3P5MT5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TCMBRG4>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBN63F6HUFFFKOMDZFIEGLD3P5M4ZAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TMNBTGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-08-28 20:14 UTC, ertugrul-yazilim commented
Siz anlatınca kolay da bi de bana sorun

28 Ağu 2025 Per 23:07 tarihinde Samil BOYALIKLI ***@***.***>
şunu yazdı:

> *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234790678>
> Anladım. Öncelikle sıfırdan harita kurgulamak zorunda değilsiniz. Mevcut
> datasete ilçeler eklenerek ilerlenebilir. PR'lara bakarsanız bir
> arkadaşımız KKTC'ni de eklediği bir versiyon yollamış mesela (
> https://github.com/ozanyerli/turkeyvisited/pull/13). Buradaki kodları
> incelerseniz, aslında contributor adayı yalnızca tr-cities.json dosyasına
> KKTC'nin koordinatlarını ve özelliklerini ekleyip turkeyvisited.js'i buna
> göre revize etmiş.
>
> Ben ne yazık ki yoğunluğumdan dolayı buna vakit ayıramam ama burada kilit
> noktanın tr-cities.json dosyası olduğunu düşünüyorum. Buradan yola
> çıkarsanız istediğiniz sonuca daha rahat ulaşabilirsiniz.
>
> Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:53
> tarihinde şunu yazdı:
>
> > *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435>
>
> > Aslında ben yazılıma sadece ilgiliyim dillere hakim değilim. Cursor ile
> > fikrimi hayata geçirmeye çalıştım o da beceremedi sizin gibi dinamik
> > harita
> > eklemeyi
> >
> > 28 Ağu 2025 Per 22:51 tarihinde Samil BOYALIKLI ***@***.***>
> > şunu yazdı:
> >
> > > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>
>
> >
> > > Anlıyorum. Gayet güzel düşünmüşsünüz, özellikle memur adaylarının
> > > kullanabileceği birşey bu. Peki hangi noktada problem oldu?
> > >
> > > Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:41
> > > tarihinde şunu yazdı:
> > >
> > > > *ertugrul-yazilim* left a comment (ozanyerli/turkeyvisited#10)
> > > > <
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>
>
> >
> > >
> > > > Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak
> > > > istiyorum
> > > > kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına
> > tercih
> > > > verdiğini türliye haritası üzerinden görsün istedim
> > > >
> > > > 28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***>
> > > > şunu yazdı:
> > > >
> > > > > *samilboyalikli* left a comment (ozanyerli/turkeyvisited#10)
> > > > > <
> > > >
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>
>
> >
> > >
> > > >
> > > > >
> > > > > Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz
> > > mısın.
> > > > > iller ve ilçeler bir arada. bir türlü yapamadım
> > > > >
> > > > > Selamlar.
> > > > >
> > > > > Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli (
> > > > > https://github.com/ozanyerli). Ben şehirlerin sayısını hem
> > arayüzden
> > > > hem
> > > > > de local storage'den sıfırlayan kısmı ekledim.
> > > > > Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım
> > > > > kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve
> > > > > isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor.
> > > > > Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir.
> > > > >
> > > > > Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz
> > etkiyi
> > > > > oluşturmayabilir ve feature creep yaparak uygulama trafiğini
> olumsuz
> > > > yönde
> > > > > etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret
> > > > ettiğime
> > > > > pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da
> dikkat
> > > > > ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor
> > olabilirim.
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016>,
>
> >
> > >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY>
>
> >
> > >
> > > >
> > > > > .
> > > > > You are receiving this because you commented.Message ID:
> > > > > ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332>,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BBN63F6XGZOILJF5HOZ2GI33P5LO5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4ZDMMZTGI>
>
> >
> > >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BUOIQJBHWL4QOZC6CDT6J6L3P5MT5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TCMBRG4>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BBN63F6HUFFFKOMDZFIEGLD3P5M4ZAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TMNBTGU>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234790678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BUOIQJEVWSJJUIRU3CLGA733P5OPJAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG44TANRXHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-08-28 20:29 UTC, samilboyalikli commented
Ben Eylül'ün ortalarına doğru biraz vakit ayırabilirim. İsterseniz projeyi
forklayın kabataslak bir biçim verelim ve ben birkaç hafta içinde ilçeleri
eklemeye çalışabilirim. Eğer forklayamazsanız benim elimde bir klon var,
onun üzerinde de yapabiliriz.

2025-09-02 21:01 UTC, MetaMsa commented
Harita GeoJson standardıyla yapılıyor. İnternetten araştırabilirsiniz bunun için harita üzerinden otomatik GeoJson çıktısı veren siteler var. Ancak her ilçe için GeoJson çıktısı almak uzun sürebilir.

> Siz anlatınca kolay da bi de bana sorun 28 Ağu 2025 Per 23:07 tarihinde Samil BOYALIKLI ***@***.***> şunu yazdı:
> […](#)
> *samilboyalikli* left a comment ([ozanyerli/turkeyvisited#10](https://github.com/ozanyerli/turkeyvisited/pull/10)) <[#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234790678)> Anladım. Öncelikle sıfırdan harita kurgulamak zorunda değilsiniz. Mevcut datasete ilçeler eklenerek ilerlenebilir. PR'lara bakarsanız bir arkadaşımız KKTC'ni de eklediği bir versiyon yollamış mesela ( #13). Buradaki kodları incelerseniz, aslında contributor adayı yalnızca tr-cities.json dosyasına KKTC'nin koordinatlarını ve özelliklerini ekleyip turkeyvisited.js'i buna göre revize etmiş. Ben ne yazık ki yoğunluğumdan dolayı buna vakit ayıramam ama burada kilit noktanın tr-cities.json dosyası olduğunu düşünüyorum. Buradan yola çıkarsanız istediğiniz sonuca daha rahat ulaşabilirsiniz. Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:53 tarihinde şunu yazdı: > *ertugrul-yazilim* left a comment ([ozanyerli/turkeyvisited#10](https://github.com/ozanyerli/turkeyvisited/pull/10)) > < [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435)> > Aslında ben yazılıma sadece ilgiliyim dillere hakim değilim. Cursor ile > fikrimi hayata geçirmeye çalıştım o da beceremedi sizin gibi dinamik > harita > eklemeyi > > 28 Ağu 2025 Per 22:51 tarihinde Samil BOYALIKLI ***@***.***> > şunu yazdı: > > > *samilboyalikli* left a comment ([ozanyerli/turkeyvisited#10](https://github.com/ozanyerli/turkeyvisited/pull/10)) > > < > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017)> > > > Anlıyorum. Gayet güzel düşünmüşsünüz, özellikle memur adaylarının > > kullanabileceği birşey bu. Peki hangi noktada problem oldu? > > > > Ertugrul K.Sahin ***@***.***>, 28 Ağu 2025 Per, 22:41 > > tarihinde şunu yazdı: > > > > > *ertugrul-yazilim* left a comment ([ozanyerli/turkeyvisited#10](https://github.com/ozanyerli/turkeyvisited/pull/10)) > > > < > > > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332)> > > > > > > Aslında konu ilçe eklerken başka bir amaçtı. Tercih ekranı yapmak > > > istiyorum > > > kişiler türkiyedeki il ve ilçeleri seçerek hangi atama noktasına > tercih > > > verdiğini türliye haritası üzerinden görsün istedim > > > > > > 28 Ağu 2025 Per 22:32 tarihinde Samil BOYALIKLI ***@***.***> > > > şunu yazdı: > > > > > > > *samilboyalikli* left a comment ([ozanyerli/turkeyvisited#10](https://github.com/ozanyerli/turkeyvisited/pull/10)) > > > > < > > > > > > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016)> > > > > > > > > > > > > > > Peki türkiyenin ilçelerinin de yer aldığı bir arayüz oluşturamaz > > mısın. > > > > iller ve ilçeler bir arada. bir türlü yapamadım > > > > > > > > Selamlar. > > > > > > > > Öncelikle ben contributor'ım. Projenin sahibi sevgili Ozan Yerli ( > > > > https://github.com/ozanyerli). Ben şehirlerin sayısını hem > arayüzden > > > hem > > > > de local storage'den sıfırlayan kısmı ekledim. > > > > Codebase'e epeydir bakmamıştım şu anda tekrar göz attım. Anladığım > > > > kadarıyla tr-cities.json dosyasında ilçelerin koordinatlarını ve > > > > isim/numaralarını tıpkı Ozan'ın yaptığı gibi eklemeniz gerekiyor. > > > > Sonrasında turkeyvisited.js'i ona göre revize etmek gerekebilir. > > > > > > > > Yalnızca şöyle bir durum var: İlçelerin eklenmesi beklediğiniz > etkiyi > > > > oluşturmayabilir ve feature creep yaparak uygulama trafiğini olumsuz > > > yönde > > > > etkileyebilir. Ben şahsen gittiğim illerde hangi ilçeleri ziyaret > > > ettiğime > > > > pek dikkat etmiyorum, aynı şekilde etrafımdaki insanların da dikkat > > > > ettiğini görmüyorum. Elbette bu benim tecrübem, yanılıyor > olabilirim. > > > > > > > > — > > > > Reply to this email directly, view it on GitHub > > > > < > > > > > > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234704016)>, > > > > > > > > > > or unsubscribe > > > > < > > > > > > https://github.com/notifications/unsubscribe-auth/BUOIQJBTRFK6SIQQHIBVYVL3P5KOFAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4YDIMBRGY> > > > > > > > > > > . > > > > You are receiving this because you commented.Message ID: > > > > ***@***.***> > > > > > > > > > > — > > > Reply to this email directly, view it on GitHub > > > < > > > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234726332)>, > > > > > > or unsubscribe > > > < > > > https://github.com/notifications/unsubscribe-auth/BBN63F6XGZOILJF5HOZ2GI33P5LO5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG4ZDMMZTGI> > > > > > > . > > > You are receiving this because you authored the thread.Message ID: > > > ***@***.***> > > > > > > > — > > Reply to this email directly, view it on GitHub > > < > [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234751017)>, > > > or unsubscribe > > < > https://github.com/notifications/unsubscribe-auth/BUOIQJBHWL4QOZC6CDT6J6L3P5MT5AVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TCMBRG4> > > > . > > You are receiving this because you commented.Message ID: > > ***@***.***> > > > > — > Reply to this email directly, view it on GitHub > < [#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234756435)>, > or unsubscribe > < https://github.com/notifications/unsubscribe-auth/BBN63F6HUFFFKOMDZFIEGLD3P5M4ZAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG42TMNBTGU> > . > You are receiving this because you authored the thread.Message ID: > ***@***.***> > — Reply to this email directly, view it on GitHub <[#10 (comment)](https://github.com/ozanyerli/turkeyvisited/pull/10#issuecomment-3234790678)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/BUOIQJEVWSJJUIRU3CLGA733P5OPJAVCNFSM6AAAAACFCJH76GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEMZUG44TANRXHA> . You are receiving this because you commented.Message ID: ***@***.***>